import '@fontsource/clear-sans/100.css'
import '@fontsource/clear-sans/300.css'
import '@fontsource/clear-sans/400.css'
import '@fontsource/clear-sans/500.css'
import '@fontsource/clear-sans/700.css'
import '@fontsource/clear-sans/100-italic.css'
import '@fontsource/clear-sans/300-italic.css'
import '@fontsource/clear-sans/400-italic.css'
import '@fontsource/clear-sans/500-italic.css'
import '@fontsource/clear-sans/700-italic.css'
import './index.css'

export { MyButton } from './components/MyButton'
export { MyCounter } from './components/MyCounter'
export { MyTitle } from './components/MyTitle'
